FROM alpine:3

LABEL maintainer="Razvan Stoica <github.com/razvanstoica89>"       version="3"       description="A minimal Docker image based on Alpine Linux 3 with curl"

# Install curl
RUN apk --no-cache add curl

# Run crond ( -f is for Foreground)
CMD ["/usr/sbin/crond", "-f"]
